server:
  port: 80
spring:
  application:
    name: enjoytrip
#datasource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/enjoytrip?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: ssafy
    password: ssafy

#mybatis  
mybatis:
  mapper-locations: mappers/*.xml
  type-aliases-package: com.ssafy.enjoytrip.*.model
#jwt.access-token.expiretime=3600000
#jwt.refresh-token.expiretime=2592000000
jwt:
  salt: "ssafy-screte-key-20240404-ssafy-screte-key-20240404-ssafy-screte-key-20240404"
  access-token:
    expiretime: 3600000  # 1시간
#    expiretime: 20000  # 20 seconds
  refresh-token:
    expiretime: 2592000000  # 30일
#    expiretime: 40000  # 40 seconds


#log
logging:
  level:
    root: info
    com.ssafy.enjoytrip: debug   